# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 09:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 18, 9, 24, 0, 227675, tzinfo=utc)),
        ),
    ]
